apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-installation
  namespace: {{ include "codefresh-runner.namespace" . }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-failed 
spec:
  template:
    spec:
      serviceAccountName: {{ include "codefresh-runner.serviceAccountName" . }}
      containers:
      - name: codefresh     
        image: {{ .Values.image.repository }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/script/install.sh"]
        env:
          {{- if .Values.env.proxy }}
          {{- range $key, $value := .Values.env.proxy }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end}}
          {{- end}}
          - name: CODEFRESH_TOKEN
            value: {{ .Values.env.codefreshToken }}
          - name: CF_ARG_KUBE_NAMESPACE
            value: {{ include "codefresh-runner.namespace" . }}
          - name: CF_ARG_KUBE_CONTEXT_NAME
            value: inClusterContext
          - name: CF_AGENT_NAME
            value: {{ .Values.env.codefreshAgentName }}
          - name: CF_URL
            value: {{ .Values.env.codefreshURL }}
          - name: CF_ARG_docker-registry
            value: {{ .Values.env.dockerRegistry }}
        volumeMounts:
        - name: install-script
          mountPath: /script/install.sh
          subPath: install.sh
      volumes:
        - name: install-script
          configMap:
            name: {{ .Release.Name }}-install-script
            defaultMode: 0777               
      restartPolicy: Never
      {{- if .Values.image.imagePullSecrets }}
      imagePullSecrets:
      {{- range $sec := .Values.image.imagePullSecrets }}
        - name: {{$sec | quote }}
      {{- end }}
      {{- end }}

  backoffLimit: 4
